---
- hosts: all
  become: true
  tasks:


  - name: update repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package (ubuntu and fedora)
    ansible.builtin.package:
      name:
         - "{{ php_package }}"
         - "{{ apache_package }}"
      state: latest
      update_cache: yes
  
    

